export function queryWhiteboardRefs(root) {
  const query = (selector) => root.querySelector(selector);

  return {
    container: query("#stage-container"),
    status: query("[data-status]"),
    activeFileLabel: query("[data-file-name]"),
    menuButton: query("[data-menu-trigger]"),
    mainMenu: query("[data-main-menu]"),
    stylePanel: query("[data-style-panel]"),
    stylePanelTitle: query("[data-style-panel-title]"),
    shapePopover: query("[data-shape-popover]"),
    structurePanel: query("[data-structure-panel]"),
    structureInputLabel: query("[data-structure-input-label]"),
    structureInput: query("[data-structure-input]"),
    linearInitPanel: query("[data-linear-init-panel]"),
    arrayRandomFields: query("[data-array-random-fields]"),
    arrayRandomCountInput: query("[data-array-random-count]"),
    graphStructureInput: query("[data-graph-structure-input]"),
    treeStructureInput: query("[data-tree-structure-input]"),
    contextMenu: query("[data-context-menu]"),
    layerPanel: query("[data-layer-panel]"),
    panelBody: query("[data-panel-body]"),
    colorInput: query("[data-control='color']"),
    fillInput: query("[data-control='fill']"),
    fillTransparentInput: query("[data-control='fill-transparent']"),
    widthInput: query("[data-control='width']"),
    brushOpacityInput: query("[data-control='brush-opacity']"),
    brushSmoothingInput: query("[data-control='brush-smoothing']"),
    brushCapInput: query("[data-control='brush-cap']"),
    brushStyleInput: query("[data-control='brush-style']"),
    arrowDoubleEndedInput: query("[data-control='arrow-double-ended']"),
    coordinateUnitSizeInput: query("[data-control='coordinate-unit-size']"),
    coordinateShowGridInput: query("[data-control='coordinate-show-grid']"),
    coordinateShowTicksInput: query("[data-control='coordinate-show-ticks']"),
    coordinateShowLabelsInput: query("[data-control='coordinate-show-labels']"),
    coordinateGridColorInput: query("[data-control='coordinate-grid-color']"),
    coordinateAxisColorInput: query("[data-control='coordinate-axis-color']"),
    coordinateLabelColorInput: query("[data-control='coordinate-label-color']"),
    brushCustomColorInput: query("[data-brush-custom-color]"),
    brushWidthSlider: query("[data-brush-width-slider]"),
    brushWidthValue: query("[data-brush-width-value]"),
    brushOpacityValue: query("[data-brush-opacity-value]"),
    brushPreviewPath: query("[data-brush-preview-path]"),
    fontSizeInput: query("[data-control='font-size']"),
    fontFamilyInput: query("[data-control='font-family']"),
    zoomLabel: query("[data-zoom]"),
    zoomButton: query("[data-zoom-trigger]"),
    zoomMenu: query("[data-zoom-menu]"),
    zoomOutButton: query("[data-zoom-out]"),
    zoomInButton: query("[data-zoom-in]"),
    imageInput: query("[data-image-input]"),
    layerList: query("[data-layer-list]"),
    inspectorSectionButtons: Array.from(root.querySelectorAll("[data-section-toggle]")),
    linearFieldInputs: {
      highlightStart: query("[data-linear-field='highlight-start']"),
      highlightEnd: query("[data-linear-field='highlight-end']"),
      highlightPointer: query("[data-linear-field='highlight-pointer']"),
    },
    linearValuesTitle: query("[data-linear-values-title]"),
    linearValuesInput: query("[data-linear-values-input]"),
    arrayAlgorithmSelect: query("[data-array-algorithm-select]"),
    arrayAlgorithmStatus: query("[data-array-algorithm-status]"),
    arrayAlgorithmSpeed: query("[data-array-algorithm-speed]"),
  };
}
