export function queryWhiteboardRefs(root) {
  const query = (selector) => root.querySelector(selector);

  return {
    container: query("#stage-container"),
    status: query("[data-status]"),
    activeFileLabel: query("[data-file-name]"),
    menuButton: query("[data-menu-trigger]"),
    mainMenu: query("[data-main-menu]"),
    stylePanel: query("[data-style-panel]"),
    stylePanelTitle: query("[data-style-panel-title]"),
    shapePopover: query("[data-shape-popover]"),
    structurePanel: query("[data-structure-panel]"),
    structureInputLabel: query("[data-structure-input-label]"),
    structureInput: query("[data-structure-input]"),
    linearInitPanel: query("[data-linear-init-panel]"),
    arrayRandomFields: query("[data-array-random-fields]"),
    arrayRandomCountInput: query("[data-array-random-count]"),
    matrixRandomFields: query("[data-matrix-random-fields]"),
    matrixRandomRowsInput: query("[data-matrix-random-rows]"),
    matrixRandomColumnsInput: query("[data-matrix-random-columns]"),
    graphStructureInput: query("[data-graph-structure-input]"),
    graphNodeScale: query("[data-graph-node-scale]"),
    treeStructureInput: query("[data-tree-structure-input]"),
    contextMenu: query("[data-context-menu]"),
    layerPanel: query("[data-layer-panel]"),
    panelBody: query("[data-panel-body]"),
    zoomLabel: query("[data-zoom]"),
    zoomButton: query("[data-zoom-trigger]"),
    zoomMenu: query("[data-zoom-menu]"),
    zoomOutButton: query("[data-zoom-out]"),
    zoomInButton: query("[data-zoom-in]"),
    imageInput: query("[data-image-input]"),
    layerList: query("[data-layer-list]"),
    inspectorSectionButtons: Array.from(root.querySelectorAll("[data-section-toggle]")),
    linearFieldInputs: {
      highlightStart: query("[data-linear-field='highlight-start']"),
      highlightEnd: query("[data-linear-field='highlight-end']"),
      highlightPointer: query("[data-linear-field='highlight-pointer']"),
    },
    linearValuesTitle: query("[data-linear-values-title]"),
    linearValuesInput: query("[data-linear-values-input]"),
    arrayAlgorithmSelect: query("[data-array-algorithm-select]"),
    arrayAlgorithmStatus: query("[data-array-algorithm-status]"),
    arrayAlgorithmSpeed: query("[data-array-algorithm-speed]"),
  };
}
